from collections import Counter

from datasets import load_dataset


DATASET_NAME = "NUSryan/TRUST-Instruct"


def load_train(cache_dir=None):
    # Loading the cached Arrow file avoids the torch shared-memory path used by
    # streaming on some macOS environments.
    kwargs = {"split": "train", "streaming": False}
    if cache_dir:
        kwargs["cache_dir"] = cache_dir
    return load_dataset(DATASET_NAME, **kwargs)


def is_generic_image_record(row):
    return row.get("image", "").startswith("LLaVA-Pretrain/")


def instruction_text(row):
    return "\n".join(
        message.get("value", "")
        for message in row.get("conversations", [])
        if message.get("from") == "human"
    )


def response_text(row):
    return "\n".join(
        message.get("value", "")
        for message in row.get("conversations", [])
        if message.get("from") == "gpt"
    )


def instruction_family(row):
    text = instruction_text(row).lower()
    if is_generic_image_record(row):
        return "generic_image"
    if "visual misinformation" in text or "manipulation" in text or "generated by ai" in text:
        return "visual"
    if "cross-modal misinformation" in text or "consistent with the text" in text:
        return "cross_modal"
    if "textual misinformation" in text or "textual distortion" in text:
        return "textual"
    return "other_dedicated"


def instruction_style(row):
    messages = row.get("conversations", [])
    if len(messages) > 2:
        return "multi_turn"
    if "step 1" in response_text(row).lower():
        return "single_turn_structured"
    return "single_turn"


def evidence_tags(row):
    text = instruction_text(row).lower()
    return {
        "direct": "<direct evidence>" in text,
        "inverse": "<inverse evidence>" in text,
        "context": "<context evidence>" in text,
    }


def final_judgment(row):
    text = response_text(row).lower()
    if "judgement: fake" in text or "judgment: fake" in text:
        return "Fake"
    if "judgement: real" in text or "judgment: real" in text:
        return "Real"
    return "missing"


def summarize_counter(counter):
    return dict(sorted(counter.items(), key=lambda item: (-item[1], item[0])))


def base_summary():
    return {
        "rows": 0,
        "families": Counter(),
        "styles": Counter(),
        "conversation_lengths": Counter(),
        "image_prefixes": Counter(),
        "id_suffixes": Counter(),
        "evidence_tags": Counter(),
        "final_judgments": Counter(),
    }
