"""AWM-style batched workflow induction with resumable local memory."""

from __future__ import annotations

import json
import re
import hashlib
from datetime import datetime, timezone
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol


FAMILIES = {"visual", "cross_modal", "textual"}
ACTIONS = {
    "no_change", "add_rule", "generalize_rule", "narrow_rule",
    "reorder_steps", "remove_unsupported_rule",
}


class TextClient(Protocol):
    model: str

    def generate(self, prompt: str) -> str: ...


@dataclass(frozen=True)
class Trajectory:
    row_id: str
    image: str
    instruction: str
    response: str
    family: str


def conversation_text(row: dict[str, Any], speaker: str) -> str:
    return "\n".join(
        str(message.get("value", ""))
        for message in row.get("conversations", [])
        if message.get("from") == speaker
    ).strip()


def family_for(row: dict[str, Any]) -> str:
    if str(row.get("image", "")).startswith("LLaVA-Pretrain/"):
        return "generic_image"
    text = conversation_text(row, "human").lower()
    if "visual misinformation" in text or "manipulation" in text or "generated by ai" in text:
        return "visual"
    if "cross-modal misinformation" in text or "consistent with the text" in text:
        return "cross_modal"
    if "textual misinformation" in text or "textual distortion" in text:
        return "textual"
    return "other_dedicated"


def to_trajectory(row: dict[str, Any]) -> Trajectory | None:
    family = family_for(row)
    instruction = conversation_text(row, "human")
    response = conversation_text(row, "gpt")
    row_id = str(row.get("id", "")).strip()
    if family not in FAMILIES or not row_id or not instruction or not response:
        return None
    return Trajectory(row_id, str(row.get("image", "")), instruction, response, family)


def format_trajectory(item: Trajectory, index: int) -> str:
    return (
        f"Trajectory #{index}\n"
        f"row_id: {item.row_id}\n"
        f"family: {item.family}\n"
        f"image: {item.image}\n"
        f"user instruction:\n{item.instruction}\n"
        f"assistant response:\n{item.response}\n"
    )


def make_batches(items: list[Trajectory], max_chars: int = 60000) -> list[list[Trajectory]]:
    if max_chars < 500:
        raise ValueError("max_chars must be at least 500")
    batches: list[list[Trajectory]] = []
    current: list[Trajectory] = []
    size = 0
    for item in items:
        rendered = format_trajectory(item, len(current) + 1)
        if current and size + len(rendered) > max_chars:
            batches.append(current)
            current, size = [], 0
        current.append(item)
        size += len(rendered)
    if current:
        batches.append(current)
    return batches


INDUCTION_PROMPT = """Given a list of multimodal misinformation-verification trajectories, extract the common workflows.

Each trajectory contains a natural language instruction, an image reference, and an assistant response that demonstrates how to solve the task. Find the repetitive subset of verification operations across multiple trajectories and extract each as a reusable workflow.

Each workflow should be a commonly reused sub-routine. Do not generate similar or overlapping workflows. Represent non-fixed elements such as people, claims, events, dates, locations, URLs, and evidence items with descriptive variable names. Do not use row IDs, filenames, labels, or external knowledge as evidence.

Return strict JSON with this shape. Prefer compact structured changes and do not
repeat trajectory text. Return at most 3 candidate changes, but preserve all
important fields: name, purpose, triggers, inputs, ordered steps, conditions,
evidence rules, decision criteria, output contract, uncertainty, and provenance.
Return at most 5 workflows and at most 5 steps per workflow. Keep the response
under roughly 2,000 output tokens. Set batch_action to no_change when nothing
new is supported. Do not rewrite the skill when batch_action is no_change.
{{
  "working_skill": "<current abstract unified skill after this batch>",
  "batch_observation": "<compact observation shared by this batch>",
  "batch_action": "no_change|add_rule|generalize_rule|narrow_rule|reorder_steps|remove_unsupported_rule",
  "candidate_changes": [
    {{
      "action": "add_rule|generalize_rule|narrow_rule|reorder_steps|remove_unsupported_rule",
      "name": "<stable rule name>", "purpose": "<purpose>",
      "triggers": ["<trigger>"], "inputs": ["<input or modality>"],
      "steps": ["<ordered abstract operation>"],
      "conditions": ["<branch or condition>"],
      "evidence_rules": ["<evidence handling rule>"],
      "decision_criteria": ["<criterion>"],
      "output_contract": "<required output>",
      "uncertainty": "<unsupported or unresolved case>",
      "supporting_row_ids": ["<supplied row_id>"]
    }}
  ],
  "updates": [
    {{
      "row_id": "<one supplied row_id>",
      "action": "no_change|add_rule|generalize_rule|narrow_rule|reorder_steps|remove_unsupported_rule",
      "observation": "<dataset-supported reusable operation or conflict>",
      "rule": "<rule text or empty string>",
      "supporting_row_ids": ["<supplied row_id>"]
    }}
  ],
  "workflows": [
    {{
      "name": "<workflow name>",
      "purpose": "<purpose>",
      "steps": ["<ordered abstract step>"],
      "conditions": ["<condition or branch>"],
      "output_contract": "<output shape>",
      "supporting_row_ids": ["<supplied row_id>"]
    }}
  ]
}}

Current skill:
{current_skill}

Current memory summary:
{memory_summary}

Tasks:
{tasks}
"""


def build_prompt(batch: list[Trajectory], current_skill: str, memory_summary: str) -> str:
    tasks = "\n".join(format_trajectory(item, i) for i, item in enumerate(batch, 1))
    return INDUCTION_PROMPT.format(
        current_skill=current_skill or "(empty; no rules induced yet)",
        memory_summary=memory_summary or "(empty)",
        tasks=tasks,
    )


def parse_json(text: str) -> dict[str, Any]:
    cleaned = text.strip()
    match = re.search(r"```(?:json)?\s*(.*?)\s*```", cleaned, re.DOTALL | re.IGNORECASE)
    if match:
        cleaned = match.group(1)
    else:
        start, end = cleaned.find("{"), cleaned.rfind("}")
        if start >= 0 and end > start:
            cleaned = cleaned[start:end + 1]
    value = json.loads(cleaned)
    if not isinstance(value, dict):
        raise ValueError("model response must be a JSON object")
    return value


def validate_result(result: dict[str, Any], batch: list[Trajectory]) -> dict[str, Any]:
    allowed = {item.row_id for item in batch}
    updates = result.get("updates", [])
    if not isinstance(updates, list):
        raise ValueError("updates must be a list")
    for update in updates:
        if not isinstance(update, dict) or update.get("row_id") not in allowed:
            raise ValueError("update contains an unknown row_id")
        if update.get("action") not in ACTIONS:
            raise ValueError("update contains an invalid action")
        supports = update.get("supporting_row_ids", [])
        if not set(supports).issubset(allowed):
            raise ValueError("supporting_row_ids contains an unknown row_id")
    result.setdefault("workflows", [])
    result.setdefault("working_skill", "")
    return result


def _read_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json_atomic(path: Path, value: Any) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")
    temporary.replace(path)


def _batch_fingerprint(batch: list[Trajectory]) -> str:
    payload = "\n".join(item.row_id + "\0" + item.instruction + "\0" + item.response for item in batch)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _append_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    with path.open("a", encoding="utf-8") as stream:
        for record in records:
            stream.write(json.dumps(record, ensure_ascii=False) + "\n")


def _merge_catalog(catalog: list[dict[str, Any]], records: list[dict[str, Any]],
                   batch_index: int) -> list[dict[str, Any]]:
    """Merge structured model output without duplicating equivalent entries."""
    by_name = {str(item.get("name", "")).strip().lower(): item
               for item in catalog if str(item.get("name", "")).strip()}
    for record in records:
        if not isinstance(record, dict):
            continue
        name = str(record.get("name", "")).strip()
        if not name:
            continue
        key = name.lower()
        supports = list(dict.fromkeys(record.get("supporting_row_ids", [])))
        existing = by_name.get(key)
        if existing is None:
            item = dict(record)
            item["supporting_row_ids"] = supports
            item["first_batch"] = batch_index
            item["last_batch"] = batch_index
            by_name[key] = item
            catalog.append(item)
        else:
            for field, value in record.items():
                if field not in {"supporting_row_ids", "action"} and value not in (None, "", []):
                    existing[field] = value
            existing["supporting_row_ids"] = list(dict.fromkeys(
                existing.get("supporting_row_ids", []) + supports))
            existing["last_batch"] = batch_index
    return catalog


def _render_skill(summary: str, rules: list[dict[str, Any]],
                  workflows: list[dict[str, Any]]) -> str:
    """Render an inspectable skill while retaining the model's compact summary."""
    lines = ["# Unified multimodal misinformation verification skill", "",
             "## Synthesized procedure", "", summary.strip() or "(no summary yet)", ""]
    if workflows:
        lines += ["## Reusable workflows", ""]
        for workflow in workflows:
            lines += [f"### {workflow.get('name', 'unnamed workflow')}",
                      str(workflow.get("purpose", "")).strip()]
            steps = workflow.get("steps", [])
            if steps:
                lines.append("Steps: " + "; ".join(str(step) for step in steps))
            for field in ("conditions", "output_contract"):
                value = workflow.get(field)
                if value:
                    rendered = "; ".join(map(str, value)) if isinstance(value, list) else str(value)
                    lines.append(f"{field.replace('_', ' ').title()}: {rendered}")
            lines.append("Supported by: " + ", ".join(workflow.get("supporting_row_ids", [])))
            lines.append("")
    if rules:
        lines += ["## Evidence and decision rules", ""]
        for rule in rules:
            lines.append(f"### {rule.get('name', 'unnamed rule')}")
            for field in ("purpose", "triggers", "inputs", "steps", "conditions",
                          "evidence_rules", "decision_criteria", "output_contract", "uncertainty"):
                value = rule.get(field)
                if value:
                    rendered = "; ".join(map(str, value)) if isinstance(value, list) else str(value)
                    lines.append(f"{field.replace('_', ' ').title()}: {rendered}")
            lines.append("Supported by: " + ", ".join(rule.get("supporting_row_ids", [])))
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def run_induction(items: list[Trajectory], client: TextClient, output_dir: Path,
                  max_chars: int = 60000) -> dict[str, Any]:
    output_dir.mkdir(parents=True, exist_ok=True)
    skill_path = output_dir / "working_unified_skill.md"
    memory_path = output_dir / "workflow_memory.jsonl"
    changes_path = output_dir / "skill_change_log.jsonl"
    rules_path = output_dir / "rule_ledger.json"
    workflows_path = output_dir / "workflow_catalog.json"
    progress_path = output_dir / "progress.json"
    cache_dir = output_dir / "cache"
    cache_dir.mkdir(parents=True, exist_ok=True)
    progress = _read_json(progress_path, {"completed_batch": 0, "api_calls": 0})
    batches = make_batches(items, max_chars=max_chars)
    current_skill = skill_path.read_text(encoding="utf-8") if skill_path.exists() else ""
    rules = _read_json(rules_path, [])
    workflows = _read_json(workflows_path, [])
    if not isinstance(rules, list):
        rules = []
    if not isinstance(workflows, list):
        workflows = []
    completed = int(progress.get("completed_batch", 0))
    if completed > len(batches):
        raise ValueError("progress is ahead of available batches")
    for batch_index, batch in enumerate(batches[completed:], completed):
        prior_memory = memory_path.read_text(encoding="utf-8")[-8000:] if memory_path.exists() else ""
        memory_summary = (
            f"completed_batches={batch_index}; rules_file={changes_path.name}\n"
            f"Prior workflow memory (use as context, do not repeat it):\n{prior_memory or '(empty)'}"
        )
        prompt = build_prompt(batch, current_skill[-12000:], memory_summary)
        batch_fingerprint = _batch_fingerprint(batch)
        prompt_fingerprint = hashlib.sha256(prompt.encode("utf-8")).hexdigest()
        cache_path = cache_dir / f"batch_{batch_index:04d}.json"
        cached = _read_json(cache_path, None)
        cache_matches = (
            cached and cached.get("batch_fingerprint") == batch_fingerprint
            and cached.get("prompt_fingerprint") == prompt_fingerprint
            and cached.get("model") == getattr(client, "model", "unknown")
        )
        retry_prompt = prompt + "\n\nThe prior response was unavailable, invalid, or truncated. Return minimal valid JSON now: use empty workflows and at most one concise change."
        retry_used = False
        if cache_matches:
            raw = cached.get("raw_response", "")
            api_call_made = False
        else:
            try:
                raw = client.generate(prompt)
            except RuntimeError:
                # Some gateway responses complete without exposing visible
                # text. Retry the same batch with a minimal-output request.
                raw = client.generate(retry_prompt)
                retry_used = True
            api_call_made = True
            _write_json_atomic(cache_path, {
                "batch": batch_index, "batch_fingerprint": batch_fingerprint,
                "prompt_fingerprint": prompt_fingerprint,
                "model": getattr(client, "model", "unknown"),
                "row_ids": [item.row_id for item in batch],
                "raw_response": raw,
            })
        try:
            result = validate_result(parse_json(raw), batch)
        except (ValueError, json.JSONDecodeError):
            # A truncated cached response must never permanently block resume.
            raw = client.generate(retry_prompt)
            retry_used = True
            api_call_made = True
            try:
                result = validate_result(parse_json(raw), batch)
            except (ValueError, json.JSONDecodeError):
                (output_dir / f"failed_batch_{batch_index}.txt").write_text(raw, encoding="utf-8")
                raise
            _write_json_atomic(cache_path, {
                "batch": batch_index, "batch_fingerprint": batch_fingerprint,
                "prompt_fingerprint": prompt_fingerprint,
                "model": getattr(client, "model", "unknown"),
                "row_ids": [item.row_id for item in batch],
                "raw_response": raw,
            })
        updates = result["updates"]
        if not updates:
            candidate_changes = result.get("candidate_changes", [])
            action = result.get("batch_action", "no_change")
            if action not in ACTIONS:
                action = "no_change"
            observation = str(result.get("batch_observation", ""))
            supports = [item.row_id for item in batch]
            updates = [{"row_id": item.row_id, "action": action,
                        "observation": observation, "rule": candidate_changes,
                        "supporting_row_ids": supports} for item in batch]
        if not updates:
            action = result.get("batch_action", "no_change")
            if action not in ACTIONS:
                action = "no_change"
            supports = [item.row_id for item in batch]
            updates = [{
                "row_id": item.row_id,
                "action": action,
                "observation": str(result.get("batch_observation", "")),
                "rule": "",
                "supporting_row_ids": supports,
            } for item in batch]
        _append_jsonl(memory_path, [{
            "batch": batch_index, "row_id": update["row_id"],
            "observation": update.get("observation", ""),
            "action": update["action"],
            "supporting_row_ids": update.get("supporting_row_ids", []),
            "candidate_changes": result.get("candidate_changes", []),
            "workflows": result.get("workflows", []),
        } for update in updates])
        accepted = [update for update in updates if update["action"] != "no_change"]
        _append_jsonl(changes_path, [{
            "batch": batch_index, "row_id": update["row_id"],
            "action": update["action"], "rule": update.get("rule", ""),
            "supporting_row_ids": update.get("supporting_row_ids", []),
        } for update in accepted])
        if accepted:
            rules = _merge_catalog(rules, result.get("candidate_changes", []), batch_index)
            # Older/short-form responses still contribute their rule text.
            fallback_rules = [{
                "name": f"rule_from_{update['row_id']}",
                "purpose": "Dataset-supported verification rule",
                "steps": [update.get("rule", "")],
                "supporting_row_ids": update.get("supporting_row_ids", []),
                "action": update["action"],
            } for update in accepted if isinstance(update.get("rule"), str) and update.get("rule")]
            rules = _merge_catalog(rules, fallback_rules, batch_index)
            workflows = _merge_catalog(workflows, result.get("workflows", []), batch_index)
            proposed_skill = str(result.get("working_skill", "")).strip()
            if proposed_skill:
                current_skill = proposed_skill
            _write_json_atomic(rules_path, rules)
            _write_json_atomic(workflows_path, workflows)
            skill_path.write_text(_render_skill(current_skill, rules, workflows), encoding="utf-8")
        progress = {"completed_batch": batch_index + 1, "total_batches": len(batches),
                    "api_calls": int(progress.get("api_calls", 0)) + int(api_call_made),
                    "model": getattr(client, "model", "unknown"),
                    "completed_row_count": sum(len(part) for part in batches[:batch_index + 1]),
                    "last_updated_utc": datetime.now(timezone.utc).isoformat(),
                    "batch_fingerprint": batch_fingerprint,
                    "cache_dir": str(cache_dir)}
        _write_json_atomic(progress_path, progress)
    return progress
